### ISSUE TITLE
Problem with empty Tags

### ISSUE THREAD

**Issue by guzur** [google/gumbo-parser#353] opened 2015-11-17 14:28 UTC
Hi all, I have a problem with bad formed HTML. I',m trying to fix the chapters of a Epub and when I find an empty tag like <a/> gumbo parser fixes wrong. This is an example the same thing ocurred when I try to fix other tags. Tidy parser and sigil parser do it right. So, Is there any option in gumbo to parse this right? Here an example:

**Original** :

```
<h2 id="ch01"><a id="page_8"/>1. Tittle</h2>
<hr/>
<p>Example Text</p>
<p>This is a example Text</p>
<hr/>
```

**Gumbo Result**:

```
<h2 id="ch01"><a id="page_8">1. Tittle</a></h2><a id="page_8">
<hr/>
<p>Example Text</p>
<p>This is a example Text</p>
<hr/>
</a><a id="page_8"></a>

```

Thank you very much.

**Comment by kevinhendricks** [comment] 2015-11-17 14:45
@guzur 
You will want to use "```" to escape your code in the above message so that people can see the code you posted.  

An epub uses xhtml parsing rules not the html5 parsing rules that gumbo uses.  Under those rules gumbo is doing exactly the right thing (ie. ignore the solidus at the end of the anchor).

To work around this Sigil has basically had to hack gumbo to deal with self closing title tags in head, to auto inject closing tags for non-void self-closed tags, and even pre-parsing and replacing non-void self-closing tags like iframe using regular expressions before passing it to gumbo. None of this is how it should be done.  

The powers that be have not specified the xhtml parsing rules as they have the html5 rules.  If they had thought about it a bit, they could have easily created a parser that handled both.   The issue is that the gumbo code is very very tightly interwoven in places (it is a state-machine of sorts).  Every time I have tried to modify it to support xhtml rules, I have gotten into trouble with unexpected consequences.  

FWIW, I would love for gumbo-parser project to add an xhtml branch so that it could be modified to support both xhtml parsing and html5 parsing in the same code-base.  As most browsers also have to deal with xhtml (xml) input (depending on the mimetype being passed end and sometimes the file extension), you would think they would be interested in adding robust xhtml parsing support.

**Comment by gsnedders** [comment] 2015-11-17 15:34
What's the point in reinventing an XML parser? Why not just use libxml2 or expat? When both the tokenizer and tree construction stages of an XML parser are relatively different, I don't see the gain in hacking Gumbo to be something it isn't?

**Comment by kevinhendricks** [comment] 2015-11-17 16:22
epub3 xhtml5 follows basically the same rules as html5 and with tokenization.  In fact the epub3 spec calls for html5 with xhtml serialization.  The problem is that standard XML parsers are *not* robust and do not recover well from not-well formed input (and there are no rules for how to recover).  Also for xhtml5, there is no dtd for an xml engine to use.  In addition, many ebook engines are based on webkit or its derivatives which can easily handle html5 code now and most browsers could use the recovery power of html5 when parsing xhtml5.

**Comment by gsnedders** [comment] 2015-11-17 16:32
XHTML5 by definition should not recover from from non-well formed input. The XHTML5 specification provides a DTD containing just entity definitions (it doesn't provide any element or attribute definitions for a validating parser). I don't think any browser has any intention to move away from strict parsers for XML content, including XHTML.

If ePub has other requirements, then we're in a situation where you need an HTML parser for HTML content, an XML parser for XHTML content, and an ePub-quasi-XHTML parser, and that's just sad. Given a lot of ePub implementations are based on WebKit, I'd be curious as to what parser they're using for ePub content, given it must presumably be open-source.

**Comment by gsnedders** [comment] 2015-11-17 16:37
FWIW, the section defining how to parse XHTML5 documents is at https://html.spec.whatwg.org/multipage/xhtml.html#parsing-xhtml-documents, which quite clearly uses an XML 1.0 4th Edition parser.

**Comment by guzur** [comment] 2015-11-17 16:40
Thank you very much for your answers. It's a very interesting information. I will try with HTML Tidy that has XHTML and HTML5 support.

Again, thank you very much.

**Comment by kevinhendricks** [comment] 2015-11-17 18:06
@gsnedders 
Your reply "XHTML5 by definition should not recover from from non-well formed input. " is simply a theoretical one.  Real-life practical applications require the ability to recover from all types of xml parsing errors.  Imagine an epub3 editor that gets handled lots of broken html 3.2, html 4, html5, and xhtml 1.0, and word docs horribly converted to html.  Something has to parse these and make sense of them. 
Also epub3 does NOT use XML 1.0 or XHTML 1.0 specs, that was epub2.    Literally the epub3 spec calls for "an xhtml serialization of html5" with not much more detail that that.

@guzur 
I did not realize that some new organization has brought Tidy up to date with html5 and xhtml5.  I thought it was abandoned long ago.  I see a new release is now out Sep 4 of this year!  Thank you for the head's up.
http://www.html-tidy.org
https://github.com/htacg/tidy-html5

**Comment by gsnedders** [comment] 2015-11-17 19:35
@kevinhendricks Then XHTML as implemented in web browsers isn't a real-life practical application? Because certainly in all browsers there is no recovery from parsing errors.

As far as ePub 3 is concerned, <https://html.spec.whatwg.org/multipage/xhtml.html#the-xhtml-syntax> would appear to define the XHTML serialization of HTML5, which by reference to XML requires a draconian parser.

**Comment by kevinhendricks** [comment] 2015-11-17 19:54
@gsnedders 
You are only talking about the specs for the display engine and not an editing/creation engine.  An editing/creation engine has to take really poorly formatted html/xhtml and create proper xhtml.  Just like gumbo does in its (and BS) screen scraping role.  Right now, our hacked gumbo does this really well and we properly serialize it to xhtml  for use in the ePub.  We then use epubcheck and flightcrew for validation.  But gumbo is just so good at recovery without losing any content (it might end up xml escaping some pieces but it doesn't lose them) that we need it to do what it does well with the addition of grokking xhtml self-closing tags on non-void elements.  We previously used a variation of Tidy to do that role but it actually lost content in not-wellformed pages.  Hopefully the new version of Tidy will help to fix a lot of those issues.  And based on the original poster of this issue, we are not the only ones.

As I said, most ebook readers are actually html based and they use a webkit derivative or some sort (they seem to handle unspecified webkit css pieces) but all have had some extra work done to make their reader "special" - or to support more and etc.  We will simply keep our own fork of gumbo and try to expand on it incrementally to create our own robust html5/xhtml5 parser.  I was just hoping gumbo would see the usefulness of such a project and open a branch to start the development process so that everyone could benefit.

Thanks!
KevinH

**Comment by nostrademons** [comment] 2015-11-17 20:43
I sympathize with the need to be tolerant of malformed input - that's why HTML5 was created, after all, and why its adoption on the web has been much, much greater than XHTML's adoption.  Most of my career has been in dealing directly with user-facing software, and users are messy; oftentimes, their expectations diverge significantly from other users, and they don't really care what an arbitrary spec says.

From Gumbo's perspective, though, deviating from the spec isn't really an option.  As you noticed, Gumbo's written as a big state machine, and it's written that way because the HTML5 spec is written as a big state machine.  Having the code follow the spec as closely as possible has resulted in a number of benefits:

1. It makes it easy to audit the code.  If you look at historical issues here, we get a number of people who report some bug in how Gumbo parses a certain construct.  With code that directly cross-references the relevant spec section and reads pretty much like the spec does, we can immediately follow the intended behavior, and either point out "According to the spec, here's how your example should be parsed" or, if there's a legitimate bug in Gumbo, update the code to conform to the spec.
2. The spec changes.  We saw this with the \<template> tag, which you helped work on.  When the basics of the parser are the same, we can just add the changes and be reasonably sure we will continue to conform, or if we don't conform, we can trace through the spec and identify where we went wrong.  With local modifications, we need to consider carefully what the other consequences of the change might be, and how it may have impacted the rest of the parser.
3. It makes it possible to verify expected output just by opening Chrome, Safari, or Firefox and inspecting the DOM trees.  We do this all the time when someone posts a report of an invalid parse.  Most of the time, they agree; when they don't, we know it's time to consult the spec and see who went wrong.
4. Hixie and the WHATWG have already put significant thought into considering the ramifications of a change, which, as you've probably noticed, can sometimes be quite complex.  I don't really want Hixie's job; my day job is product design for a startup, and I've got my head full just considering the ramifications of our own product choices.

I think that given the different user constraints, your existing solution of forking Gumbo and making local modifications to support what your users do is probably the best we can hope for.  I also don't mind if other epub3 users would rather use your fork or Tidy or some other package for parsing their ebooks.  Just remember that there are consequences to deviating from the spec: it will be additional maintenance work if & when the spec changes, you may have angry users on the other side who expect that anchor tag to continue until it's closed because that's how it works in Webkit, or other parsers (I'm thinking of Tidy here, specifically) may not actually conform to the HTML5 specification in other ways.

Incidentally, I once had similar local modifications to the HTML parsing rules to support the internal project at Google that spawned Gumbo.  They had a similar requirement: users wanted to write "HTML", but they wanted to write HTML that conformed to their mental model of how it worked and not what the spec actually said (and to be fair, as a user of this internal project, I thought the consequences of the HTML5 rules were pretty brain-dead).  I ended up ripping this code out before open-sourcing, because it was a huge maintenance burden (it would've made the template tag impossible, for example), and their needs eventually diverged enough that they wanted to go with a completely custom parser anyway.

**Comment by kevinhendricks** [comment] 2015-11-17 21:13
@nostrademons 
Well it was worth a shot!   ;-)   At some point when you have some free time, I would love to pick your brain over how and where best to inject new states (if needed) into the machine to enable it to recognize a trailing solidus more properly (or carry along more info if the state needs it) and determine if a pop at that point can be done directly without disturbing the remainder of the machine.  In some of the svg and mathml code (ie. in a in a foreign state), the code must obviously handle non-void self-closing tags well.  I cringe when I look at the length of the handle_in_body code now and wonder if there is any sane way to deal issues in that state.  I was able to do it in head but with a limited set of tags. I  ended up injecting end tags only when needed in the main parse loop near the very end of parse.c to prevent disturbing anything much.    It handles most cases fine but the iframe code immediately transitions into another state and doesn't return to the main parser loop immediately making injection fail for self-closing iframes.  I guess I will have to schematically try and understand the state sequences better.  
Thanks ...

**Comment by gsnedders** [comment] 2015-11-17 22:42
(Sorry @nostrademons for taking this a bit further off-topic. Tell me to shut up at will. :))

@kevinhendricks Where's the broken XHTML coming from, wrt the editing side of things? How is it ending up in a state where it's neither HTML nor XHTML? I hear plenty of ePub people talking about this, though I will say I still don't really understand what's going on! What parts of ePub are de-facto relying on lax parsing? I know calibre at least has felt forced to use a lax parser, obviously for the final document and nothing in the editing toolchain.

When it comes to lax parsing of XML, dropping a mention of https://github.com/annevk/xml5 is probably somewhat relevant, though it is pretty abandoned. I agree with @nostrademons that it makes more sense to do it in a separate codebase, though.

FWIW, @kevinhendricks: the spec tokenizer always sets the trailing-solidus flag, regardless of whether the element is void or not (except in foreign content, it's totally ignored unconditionally, except for a parse error when not on a void element). Not looked at Gumbo for a while so may well not be able to help.

**Comment by kevinhendricks** [comment] 2015-11-17 23:36
@gsnedders 
My project is Sigil.  It is an epub editor.  It allows authors to create their own epubs, including editing in a browser like window for simple wysiwyg editing and typing code directly into code editor.  People can import html, xhtml, and even old html3.2 (Amozon Mobi ebooks use an old dialect of html3) and even horrible html generated from Word.   They then clean it and start to add images, links, fonts, and css to create an epub.  Auto create a toc.ncx, add html toc, cover images with svg to expand an image to fill any ereader screen, etc. The input you get from mobi ebooks and many older ebook formats is literally horrible. When you add to that xhtml entered by users who forget to properly close tags, you end up with tag soup at best at times.  Sigil creates a constantly updated preview window to show each chapter while it is being edited.

Gumbo properly sets the trailing solidus info and uses it when not "acknowledged" to properly record the error so that info is valid (at least at times).

**Closed** 2023-02-15 22:57 UTC
