### ISSUE TITLE
assert failure in handle_in_template

### ISSUE THREAD

**Issue by lcamtuf** [google/gumbo-parser#330] opened 2015-04-27 02:14 UTC
printf '&lt;template&gt;\0' >foo.html

Causes assertion failure in:

prettyprint: src/parser.c:3596: _Bool handle_in_template(GumboParser *, GumboToken *): Assertion `0' failed.

Edit: fixed broken markup

**Comment by nostrademons** [comment] 2015-05-01 01:13
Should be fixed with a test in #335.  Root cause was a missing check for GUMBO_TOKEN_NULL in the code.

**Closed by nostrademons** 2015-05-01 01:13 UTC
