### ISSUE TITLE
Empty document when page has empty title element

### ISSUE THREAD

**Issue by daurnimator** [google/gumbo-parser#326] opened 2015-04-08 06:25 UTC
Also filed at: https://github.com/craigbarnes/lua-gumbo/issues/42

It appears that lua-gumbo will emit an empty document if it encounters an empty title element:

```
$ lua5.1  -e 'print(require"gumbo".parse("<head><title/></head><body>hi</body>").body.outerHTML)'
<body></body>
```

```
$ lua5.1  -e 'print(require"gumbo".parse("<head><title>asd</title></head><body>hi</body>").body.outerHTML)'
<body>hi</body>
```

Not sure if this is an issue with gumbo in general or just lua-gumbo

I'm using the most recent release (gumbo 0.9.3)

**Comment by nostrademons** [comment] 2015-04-28 03:54
This was closed as not a bug (title tags are not self-closing) on lua-gumbo.

**Closed by nostrademons** 2015-04-28 03:54 UTC
